### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by sliker2013** [Shoxxo/CrixnetBugtracker#1]
Guten Tag, 

Ich wollte mal einen kleinen (Großen) Bug Melden 

Alle Items und Gossip Menüs sowie /DBC Files auf Englisch sind obwohl ich einen DEde client habe ;)

Währe nett wenn man sich die mühe macht 

MFG Sliker

**Comment by Shoxxo** [comment]
Bitte die Vorlage einhalten ;)

Danke!
